export const BotReplies: string[] = [
    "SHUT UP AND PLAY, YOU BLUNDERING MORON",
    "Your moves are dumber than your mom's shopping list",
    "Bro, I'd rather lose to a toddler than read your garbage",
    "Keep typing, you limp-wristed pawn pusher",
    "Your king is more exposed than your sister's bedroom",
    "Type less, you drooling retard",
    "Bro discovered chat before he discovered brains",
    "Your position is uglier than your family reunion",
    "I'm checkmating your worthless ego",
    "Shut your trap or I'll hang your queen like your dignity",
    "You play like a virgin at a strip club - clueless",
    "My rook just crushed your bishop, you weakling",
    "Keep talking trash, I'll make you resign like a coward",
    "Your opening is lamer than a three-legged dog",
    "Bro, your brain is on permanent vacation",
    "I'd castle faster than you chase girls",
    "Your messages are as pointless as your tiny manhood",
    "Get lost and develop, you inbred noob",
    "Your king begs for mate louder than your whining",
    "I'm owning you harder than your dad owns the remote",
    "Type again and I'll sacrifice your pride to my knight",
    "You blunder more than you blink, you waste of space",
    "Bro thinks he's a grandmaster? You're a janitor",
    "Your position screams disaster - fix it, loser",
    "Keep chatting, you're speedrunning your humiliation",
    "My eval bar towers over your mom's IQ",
    "Shut up, you donkey-brained elo clown",
    "Your pawns hang like your self-respect",
    "I'd rather eat dirt than let you win, you reject",
    "Bro typed all that just to hang his rook - genius",
    "Your chess is as dead as your social life, loner",
    "Ignore chat, touch a piece or stay a loser",
    "You're getting crushed by a bot, you pathetic stain",
    "My queen's forking your ego and your hopes",
    "Keep going, maybe words will grow you a brain",
    "Your king's armor is thinner than your wallet",
    "Bro, you're a walking zugzwang disaster",
    "I'd promote faster than you get a date",
    "Shut your mouth, your position's a joke",
    "You talk tough but play like a scared kitten",
    "My knights leap over your entire bloodline",
    "Resign now or suffer, you crybaby",
    "Your blunders are sloppier than your grooming",
    "Chat's for champions - you're a chump",
    "Bro really thought roasting saves his skin",
    "Your structure crumbles like your confidence",
    "I'm collecting your pieces like your failures",
    "Type less, you spineless wonder",
    "Your mom's calling - she wants her brain cells back",
    "Keep messaging, it's your white flag",
    "You're one move from total embarrassment",
    "Forget theory, you're getting demolished",
    "Bro's chat strong, chess game: embarrassing",
    "Your bishop's pinned like your dreams",
    "Shut up and play or stay exposed, fool",
    "You're trashier than yesterday's garbage",
    "Your dad must be proud of that last blunder",
    "Keep dreaming, you're my practice dummy",
    "Your queen's hanging like your future",
    "Bro, chat won't save your sinking ship",
    "You're dumber than a bag of hammers",
    "My pawns outsmart your whole army",
    "Type your obituary next, it's over",
    "Your position is a clown show",
    "Loser alert: that's you in chat",
    "I'd resign before playing like you",
    "Your ego's bigger than your blunder count",
    "Keep yapping, it hides nothing",
    "You're the king of hanging pieces",
    "Bro's family tree is a straight line",
    "Shut it, your moves are criminal",
    "My engine laughs at your 'strategy'"
];